### ISSUE TITLE
Adding Julia data export example

### ISSUE THREAD

**Issue by BradyPlanden** [Battery-Intelligence-Lab/galv#96]
**Describe the solution you'd like**
It would be great to add a Julia data export example to Galv.

**Comment by mjaquiery** [comment]
Our current workflow is:
1. Generate API spec
2. Use that to create API clients automatically in a large range of languages
3. Show examples of how to use betrayed clients for some languages.

Currently the schema isn't specified quite right for the clients to use (step 1 needs tweaking). OnOnce that works, we'll add a Julia example alongside Python and Matlab.

**Comment by mjaquiery** [comment]
#62 won't be fixed, so if we still want a Julia hint code block (like there is for Matlab) then it'll have to be custom-written. 

Should I do this when I do it for Python, @BradyPlanden ?

**Comment by BradyPlanden** [comment]
Hi Matt,

Yeah I just read your comment on #62. This seems like the best way forward for the moment. That would be appreciated, if you want a hand with it give me a shout!
